name: Kaggle Dataset Sync

on:
  push:
    branches:
      - main

jobs:
  sync_kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Set Kaggle API Credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"ahamedinmotion\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Ensure Dataset Directory Exists
        run: |
          mkdir -p dataset
          echo "Dummy file to ensure directory is not empty" > dataset/dummy.txt

      - name: Create Kaggle Metadata File
        run: |
          cat << EOF > dataset/dataset-metadata.json
          {
            "title": "Brain Stroke Scans",
            "id": "ahamedinmotion/brain-stroke-scans",
            "licenses": [{"name": "CC0-1.0"}]
          }
          EOF

      - name: Upload Dataset to Kaggle
        run: kaggle datasets version -p dataset --dir-mode zip -m "Updated dataset"
